name: Build Windows EXE

on: [push]

jobs:

  build-windows:

    runs-on: windows-latest

    defaults:
      run:
        working-directory: Projects/Company_Valuation_And_Investment_Calculator

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onedir ^
          --add-data "databases;databases" ^
          --name CompanyValuationTerminal ^
          main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CompanyValuationTerminal-Windows
          path: Projects/Company_Valuation_And_Investment_Calculator/dist/